FROM node:10

WORKDIR /app

ARG EVENTOR_API_KEY_SE
ARG EVENTOR_API_KEY_AU
ARG SLACK_WEBHOOK

ENV EVENTOR_API_KEY_SE $EVENTOR_API_KEY_SE
ENV EVENTOR_API_KEY_SE $EVENTOR_API_KEY_AU
ENV SLACK_WEBHOOK $SLACK_WEBHOOK
ENV ENV LIVE

ADD ./Server/package.json ./
ADD ./Server/yarn.lock ./
RUN yarn install

ADD ./Server/tsconfig.json ./
ADD ./Server/.babelrc ./
ADD ./Server/src ./src

RUN yarn build

EXPOSE 4000

CMD node ./build
