# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

def getPackageVersion()
  file = File.open("../../package.json")
  data = JSON.parse(file.read)
  return data["version"]
end

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )

    gradle(
      task: 'assemble',
      build_type: 'release'
    )

    upload_to_play_store(
      track: 'production',
      release_status: 'draft',
      version_name: getPackageVersion
    )
  end

  desc "Build a release APK and move it to the desktop"
  lane :apk do
    gradle(
      task: 'assemble',
      build_type: 'release'
    )

    sh "mv ../app/build/outputs/apk/release/app-release.apk ~/Desktop"
  end
end
