version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
    deploy-server:
        executor:
            name: node/default
        steps:
            - checkout

            - setup_remote_docker

            - run:
                name: Disable known hosts for the ssh domain
                command: |
                    echo "Host ${SSH_DOMAIN}
                    StrictHostKeyChecking no
                    UserKnownHostsFile /dev/null" > ~/.ssh/config

            - run:
                name: Install sshpass
                command: sudo apt-get install sshpass

            - run:
                name: Set up Docker
                command: docker login --username=${CANISTER_ID} --password=${CANISTER_PASSWORD} cloud.canister.io:5000

            - run:
                name: Build server container
                command: cd ./Server && yarn docker:latest

            - run:
                name: Set up Docker on server
                command: |
                    sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USER}@${SSH_DOMAIN} -p ${SSH_PORT}
                    "docker login --username=${CANISTER_ID} --password=${CANISTER_PASSWORD} cloud.canister.io:5000"

            - run:
                name: Pull changes on server
                command: |
                    sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USER}@${SSH_DOMAIN} -p ${SSH_PORT}
                    "cd ${PROJECT_ROOT} && git stash && git pull"

            - run:
                name: Rebuild the Docker containers and restart server
                command: |
                    sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USER}@${SSH_DOMAIN} -p ${SSH_PORT}
                    "cd ${PROJECT_ROOT} && docker-compose -f docker-compose.live.yml up --build -d"
workflows:
    deploy-server:
      jobs:
        - deploy-server
