version: 2.1

jobs:
  lint-app:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          name: Install yarn
          command: cd ./App && yarn install
      - run:
          name: Lint app
          command: cd ./App && yarn lint

  deploy-server:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          name: Deploy with CapRover
          command: |
            npx caprover deploy \
              --caproverUrl $CAPROVER_URL \
              --caproverPassword $CAPROVER_PASSWORD \
              --caproverApp $CAPROVER_APP \
              --branch $CAPROVER_BRANCH

workflows:
  linting:
    jobs:
      - lint-app
  deploy:
    jobs:
      - deploy-server:
          filters:
            branches:
              only:
                - master
