version: 2.1

jobs:
    deploy-server:
        docker:
            -
                image: "237763290421.dkr.ecr.eu-north-1.amazonaws.com/deploy:latest"
                aws_auth:
                    aws_access_key_id: $AWS_ACCESS_KEY_ID
                    aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "fe:fc:8f:b8:00:d8:ba:d4:7c:e9:bb:10:92:2d:0e:1d"

            - checkout

            - setup_remote_docker

            - run:
                name: Disable known hosts for the ssh domain
                command: |
                    echo "Host ${SSH_DOMAIN}
                    StrictHostKeyChecking no
                    UserKnownHostsFile /dev/null" > ~/.ssh/config

            - run:
                name: Set up Docker
                command: eval $(aws ecr get-login --no-include-email --region=eu-north-1)

            - run:
                name: Build server container
                command: cd ./Server && yarn docker:latest

            - run:
                name: Authenticate ECR
                command: |
                    ssh ${SSH_USER}@${SSH_DOMAIN} -p ${SSH_PORT} "aws ecr get-login --no-include-email --region=eu-north-1"

            - run:
                name: Pull changes on server
                command: |
                    ssh ${SSH_USER}@${SSH_DOMAIN} -p ${SSH_PORT} "cd ${PROJECT_ROOT} && git stash && git pull"

            - run:
                name: Rebuild the Docker containers and restart server
                command: |
                    ssh ${SSH_USER}@${SSH_DOMAIN} -p ${SSH_PORT} "cd ${PROJECT_ROOT} && docker-compose -f docker-compose.live.yml up --build -d"
workflows:
    deploy-server:
      jobs:
        - deploy-server
