source "https://rubygems.org"


# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '2.7.6'

gem 'cocoapods', '~> 1.12'

gem 'fastlane'
gem 'fastlane-plugin-versioning'
gem 'fastlane-plugin-increment_version_code'
gem 'fastlane-plugin-appcenter'

gem 'dotenv', '~> 2.8'