source "https://rubygems.org"


# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '2.7.6'

# Cocoapods 1.15 introduced a bug which break the build. We will remove the upper
# bound in the template on Cocoapods with next React Native release.
gem 'cocoapods', '>= 1.13', '< 1.15'
gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'

gem 'fastlane'
gem 'fastlane-plugin-versioning'
gem 'fastlane-plugin-increment_version_code'
gem 'fastlane-plugin-appcenter'

gem 'dotenv', '~> 2.8'