services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        command: npm run dev
        ports:
            - 3037:3001
            - 3036:3000
        volumes:
            - ./src:/app/src/
        depends_on:
            - redis
        env_file:
            - .env
        environment:
            - NODE_ENV=development
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
