version: '3.7'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        command: npm run dev
        ports:
            - 3001:3001
        volumes:
            - ./src:/app/src/
        depends_on:
            - redis
        env_file:
            - .env
        environment:
            - NODE_ENV=development
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
    redis-commander:
        image: rediscommander/redis-commander:latest
        depends_on:
            - redis
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8002:8081'
