services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: sh -c "npx nodemon -L -e ts -w ./src -x 'ts-node -r tsconfig-paths/register src/index.ts' | npx pino-pretty"
        ports:
            - 3037:3001
            - 3036:3000
        volumes:
            - ./src:/app/src/
        env_file:
            - .env
        environment:
            - NODE_ENV=development
        depends_on:
            - redis
            - db
    redis:
        image: redis:latest
        ports:
            - '6379:6379'

    db:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - db_data:/var/lib/postgresql/data
            
volumes:
    db_data:
