version: '3.7'
services:
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
    redis-commander:
        image: rediscommander/redis-commander:latest
        depends_on:
            - redis
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8002:8081'
