version: '3.7'
services:
    server:
        restart: always
        image: 237763290421.dkr.ecr.eu-north-1.amazonaws.com/liveol:latest
        ports:
            - "4000:4000"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
    redis:
        restart: always
        image: redis:latest
        ports:
            - "6379:6379"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
