require 'json'
require 'dotenv'

default_platform(:ios)

def getPackageVersion()
  file = File.open("../../package.json")
  data = JSON.parse(file.read)
  return data["version"]
end

platform :ios do
  before_all do
    Dotenv.load('../../.env.local')
  end

  desc "Push a new release build to Testflight"
  lane :release do
    xcodeproj = "LiveOL.xcodeproj"
    scheme = "LiveOL"

    api_key = app_store_connect_api_key(
      key_id: ENV["IOS_KEY_ID"],
      issuer_id: ENV["IOS_ISSUER_ID"],
      key_filepath: Dir.pwd + "/../../" + ENV["IOS_KEY_FILENAME"],
    )

    increment_version_number_in_plist(
      version_number: getPackageVersion,
      scheme: scheme
    )

    increment_build_number(xcodeproj: xcodeproj)

    clear_derived_data

    build_app(
      workspace: "LiveOL.xcworkspace",
      xcargs: "-allowProvisioningUpdates",
      scheme: scheme
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )
  end
end
